### PR TITLE
#35: angus activation does not provide its services in an OSGi environment

### LINKED ISSUE #35: angus activation does not provide its services in an OSGi environment
Angus activation provides an implementation of the Jakarta Activation Specification. The relationship between the jar providing the API and its implementation is established at runtime using the service discovery mechanism. This has been implemented correctly for non-OSGI environments by adding the files `META-INF/services/jakarta.activation.spi.MimeTypeRegistryProvider` and `osgi.serviceloader=jakarta.activation.spi.MailcapRegistryProvider` to the jar.

Due to OSGi's classpath isolation, service discovery requires additional information in `MANIFEST.MF`. The `jakarta.activation-api` has correctly added this information (`Require-Capability` header referencing the interfaces enumerated above). Angus activation should have the corresponding (matching) `Provide-Capability` header, but it does not.

The buggy information provided in angus-activation's `Provide-Capability` header is:
```
osgi.serviceloader;osgi.serviceloader="org.eclipse.angus.activation.MailcapRegistryProviderImpl";register:="org.eclipse.angus.activation.MailcapRegistryProviderImpl"
osgi.serviceloader;osgi.serviceloader="org.eclipse.angus.activation.MimeTypeRegistryProviderImpl";register:="org.eclipse.angus.activation.MimeTypeRegistryProviderImpl"
```
The name after `osgi.serviceloader=` must be the type of the [service provided](https://docs.osgi.org/specification/osgi.enterprise/7.0.0/service.loader.html#d0e61248) (i.e. it must match the file name used in `META-INF/services/`). The name after `register:=` must be the implementation class (i.e. the content of the file in in `META-INF/services/`). (The latter information is provided correctly, but [could be omitted](https://docs.osgi.org/specification/osgi.enterprise/7.0.0/service.loader.html#d0e61248)). 

The bug is present in both 1.X and 2.X.

### PR DESCRIPTION
**Pull request by lukasj**
fixes #35

### CODE REVIEW

**Review by mnlipp — APPROVED** [review]
Looks good. Tried it, works. The providers are registered as services of the expected type now. My sample application could (finally) be started without hk2.osgi-resource-locator.

**Comment by lukasj** [comment]
Thanks for testing this. I'll apply the same change to other projects in the next few days. Thanks!

**Comment by mnlipp** [comment]
> Thanks for testing this. I'll apply the same change to other projects in the next few days. Thanks!

BTW I'm pondering about this since yesterday: why did you add these `osgi.service;objectClass=...` "statements"?

**Comment by lukasj** [comment]
TBH I don't recall. I think I've added OSGi dependency and annotations, let felix generate the manifest, took what was there in the generated manifest and removed dependency etc. Do you think it can go away?

**Comment by mnlipp** [comment]
> Do you think it can go away?

Yes, see https://github.com/eclipse-ee4j/angus-activation/pull/37. Going to test for angus mail as well.

**Pull request merged**
